### ISSUE TITLE
RuntimeError: Distributed package doesn't have NCCL built in

### ISSUE THREAD

**Issue by MohammedAljahdali** [ray-project/ray_lightning_accelerators#13]
Hey, I am having an issue when I run `trainer.fit` with the accelerator I get the following error:
```
2021-03-08 13:45:49,085 INFO services.py:1172 -- View the Ray dashboard at http://127.0.0.1:8265
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.
Global seed set to 1234
initializing ddp: GLOBAL_RANK: 0, MEMBER: 1/1
Traceback (most recent call last):
  File "train.py", line 26, in cli_main
    train(None, cfg)
  File "train.py", line 102, in train
    trainer.fit(model, datamodule=dm)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\ray_lightning\ray_ddp.py", line 184, in train
    results = process_results(futures, queue)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\ray_lightning\util.py", line 103, in process_results
    ray.get(ready)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\_private\client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::RayExecutor.execute() (pid=27620, ip=192.168.8.100)
  File "python\ray\_raylet.pyx", line 480, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 432, in ray._raylet.execute_task.function_executor
  File "C:\Users\Mohammed\AppData\Roaming\Python\Python38\site-packages\ray\function_manager.py", line 556, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\ray_lightning\ray_ddp.py", line 31, in execute
    return fn(*args, **kwargs)
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\ray_lightning\ray_ddp.py", line 218, in train_remote
    super(RayAccelerator, self).ddp_train(
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\pytorch_lightning\accelerators\ddp_spawn_accelerator.py", line 127, in ddp_train
    self.init_ddp_connection(
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\ray_lightning\ray_ddp.py", line 232, in init_ddp_connection
    torch.distributed.init_process_group(
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\torch\distributed\distributed_c10d.py", line 503, in init_process_group
    _update_default_pg(_new_process_group_helper(
  File "C:\Users\Mohammed\AppData\Local\conda\conda\envs\htts\lib\site-packages\torch\distributed\distributed_c10d.py", line 597, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in
```

**Comment by amogkam** [comment]
@MohammedAljahdali Pytorch on Windows does not support the NCCL backend. Can you use the gloo backend instead.

![image](https://user-images.githubusercontent.com/8068268/110354070-9ee8d300-7fec-11eb-87ad-9c5e27b33d89.png)

You can find more information [here](https://pytorch-lightning.readthedocs.io/en/stable/advanced/multi_gpu.html#select-torch-distributed-backend) and [here](https://pytorch.org/docs/stable/distributed.html)

**Comment by Roffmkkkd** [comment]
Hi, @MohammedAljahdali, I met the same problem when I use vscode as my IDE, and I have sovle this.
add the follow code in launch.json:
"env": {"PL_TORCH_DISTRIBUTED_BACKEND":"gloo"},
Windows must use gloo method.....
Weird problem.

**Comment by shahnazari** [comment]
> Hi, @MohammedAljahdali, I met the same problem when I use vscode as my IDE, and I have sovle this. add the follow code in launch.json: "env": {"PL_TORCH_DISTRIBUTED_BACKEND":"gloo"}, Windows must use gloo method..... Weird problem.

Right. So mainly if a person encounters such runtime error, there is a backend=nccl in a piece of code somewhere where they should change it to backend=gloo to run on Windows.

**Comment by Roffmkkkd** [comment]
邮件已收到啦，感谢来信！

**Comment by amogkam** [comment]
@shahnazari if you just set the environment variable `PL_TORCH_DISTRIBUTED_BACKEND=gloo`, then your script would use the gloo backend and not nccl. There shouldn't be any changes needed to the code! Let me know if this works!

**Comment by TalTaiber** [comment]
> @shahnazari if you just set the environment variable `PL_TORCH_DISTRIBUTED_BACKEND=gloo`, then your script would use the gloo backend and not nccl. There shouldn't be any changes needed to the code! Let me know if this works!

Saved my day 👍

**Comment by Roffmkkkd** [comment]
邮件已收到啦，感谢来信！

**Comment by iamgmujtaba** [comment]
You can also write in the main python script
import os
os.environ["PL_TORCH_DISTRIBUTED_BACKEND"] = "gloo"

**Comment by ahmedbr** [comment]
I'm using accelerate, and the solution of adding the environment variable `PL_TORCH_DISTRIBUTED_BACKEND=gloo` didn't work for me on Windows. Any other suggestion available?

**Comment by Roffmkkkd** [comment]
邮件已收到啦，感谢来信！

**Comment by pokecheater** [comment]
> You can also write in the main python script
> 
> ```python
> import os
> os.environ["PL_TORCH_DISTRIBUTED_BACKEND"] = "gloo"
> ```

Saved my day <3

**Comment by RoushanakRahmat** [comment]
I am having this problem and none of the suggested solutions worked

dist_util.setup_dist()---> RuntimeError: Distributed package doesn't have NCCL built in

**Comment by Roffmkkkd** [comment]
邮件已收到啦，感谢来信！

**Comment by GO-Loc-GO** [comment]
I was using Ray to train a PyTorch-built CNN-LSTM model using the GPU on my laptop, which has Windows 10 installed. I met the same issue that NCLL is not supported on Windows, but the above ways did not seem to work for me or I might have done them the wrong way.

However, I still resolved the issue using the following code in which the '**torch_config**' parameter was the key thing I added to my original code: 
    scaling_config = ScalingConfig(num_workers=1, use_gpu=True)
    **torch_config = TorchConfig(backend="gloo")**
    trainer = TorchTrainer(
        train_loop_per_worker=train_loop_per_worker,
        **torch_config=torch_config**,
        scaling_config=scaling_config,
        datasets={"train": train_dataset}
    )
I hope this helps anyone meeting the same issue on Windows OS.

**Comment by Roffmkkkd** [comment]
邮件已收到啦，感谢来信！
